name: Build demo.db
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: make demo.db
      - uses: actions/upload-artifact@v4
        with:
          path: demo.db
